language: c

addons:
  apt:
    sources:
     - hvr-ghc
    packages:
     - cabal-install-1.16
     - cabal-install-1.18
     - cabal-install-1.22
     - cabal-install-1.24
     - cabal-install-head

     - ghc-7.0.4
     - ghc-7.2.2
     - ghc-7.4.2
     - ghc-7.6.3
     - ghc-7.8.4
     - ghc-7.10.3
     - ghc-8.0.1
     - ghc-head

script:
  ./build.sh
